# S09 T02: Aprenentatge Supervisat - Regressions

Descripció:

Anem a practicar i a familiaritzar-nos amb regressions

## NIVELL 1


### Exercici 1
Crea almenys tres models de regressió diferents per intentar predir el millor possible l’endarreriment dels vols (ArrDelay) de DelayedFlights.csv.



In [1]:
# Crido a les llibreries necessàries
# Faig entrar l'arxiu CSV gràcies a pandas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

delayedFlightsAmbNaN = pd.read_csv(r'C:\Users\Anna\DataScience\SPRINTS\SPRINT 9\DelayedFlights\DelayedFlights2.csv')


# Elimino els NaN per fer el dataset algo més petit
delayedFlights = delayedFlightsAmbNaN.dropna()

display(delayedFlights)


Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
3                 4  2008      1           3          4   1829.0        1755   
5                 6  2008      1           3          4   1937.0        1830   
7                11  2008      1           3          4   1644.0        1510   
9                16  2008      1           3          4   1452.0        1425   
11               18  2008      1           3          4   1323.0        1255   
...             ...   ...    ...         ...        ...      ...         ...   
1936751     7009705  2008     12          13          6    921.0         830   
1936752     7009709  2008     12          13          6   1552.0        1520   
1936753     7009710  2008     12          13          6   1250.0        1220   
1936754     7009717  2008     12          13          6    657.0         600   
1936755     7009718  2008     12          13          6   1007.0         847   

         ArrTime  CRSArrTime UniqueCarrier  ...  TaxiIn TaxiOut  Cancelled  \
3         1959.0        1925            WN  ...     3.0    10.0          0   
5         2037.0        1940            WN  ...     3.0     7.0          0   
7         1845.0        1725            WN  ...     6.0     8.0          0   
9         1640.0        1625            WN  ...     7.0     8.0          0   
11        1526.0        1510            WN  ...     4.0     9.0          0   
...          ...         ...           ...  ...     ...     ...        ...   
1936751   1112.0        1008            DL  ...     8.0    21.0          0   
1936752   1735.0        1718            DL  ...     9.0     7.0          0   
1936753   1617.0        1552            DL  ...     9.0    18.0          0   
1936754    904.0         749            DL  ...    15.0    34.0          0   
1936755   1149.0        1010            DL  ...     8.0    32.0          0   

         CancellationCode  Diverted  CarrierDelay  WeatherDelay NASDelay  \
3                       N         0           2.0           0.0      0.0   
5                       N         0          10.0           0.0      0.0   
7                       N         0           8.0           0.0      0.0   
9                       N         0           3.0           0.0      0.0   
11                      N         0           0.0           0.0      0.0   
...                   ...       ...           ...           ...      ...   
1936751                 N         0          51.0           0.0     13.0   
1936752                 N         0           0.0           0.0      0.0   
1936753                 N         0           3.0           0.0      0.0   
1936754                 N         0           0.0          57.0     18.0   
1936755                 N         0           1.0           0.0     19.0   

        SecurityDelay  LateAircraftDelay  
3                 0.0               32.0  
5                 0.0               47.0  
7                 0.0               72.0  
9                 0.0               12.0  
11                0.0               16.0  
...               ...                ...  
1936751           0.0                0.0  
1936752           0.0               17.0  
1936753           0.0               22.0  
1936754           0.0                0.0  
1936755           0.0               79.0  

[1247486 rows x 30 columns]

In [2]:
delayedFlights.count()

Unnamed: 0           1247486
Year                 1247486
Month                1247486
DayofMonth           1247486
DayOfWeek            1247486
DepTime              1247486
CRSDepTime           1247486
ArrTime              1247486
CRSArrTime           1247486
UniqueCarrier        1247486
FlightNum            1247486
TailNum              1247486
ActualElapsedTime    1247486
CRSElapsedTime       1247486
AirTime              1247486
ArrDelay             1247486
DepDelay             1247486
Origin               1247486
Dest                 1247486
Distance             1247486
TaxiIn               1247486
TaxiOut              1247486
Cancelled            1247486
CancellationCode     1247486
Diverted             1247486
CarrierDelay         1247486
WeatherDelay         1247486
NASDelay             1247486
SecurityDelay        1247486
LateAircraftDelay    1247486
dtype: int64

In [3]:
delayedFlights.shape

(1247486, 30)

In [4]:
delayedFlights.describe()

Unnamed: 0       Year         Month    DayofMonth     DayOfWeek  \
count  1.247486e+06  1247486.0  1.247486e+06  1.247486e+06  1.247486e+06   
mean   3.319515e+06     2008.0  6.065399e+00  1.572542e+01  3.980082e+00   
std    2.079531e+06        0.0  3.508937e+00  8.793008e+00  1.993270e+00   
min    4.000000e+00     2008.0  1.000000e+00  1.000000e+00  1.000000e+00   
25%    1.484624e+06     2008.0  3.000000e+00  8.000000e+00  2.000000e+00   
50%    3.224052e+06     2008.0  6.000000e+00  1.600000e+01  4.000000e+00   
75%    4.921396e+06     2008.0  9.000000e+00  2.300000e+01  6.000000e+00   
max    7.009718e+06     2008.0  1.200000e+01  3.100000e+01  7.000000e+00   

            DepTime    CRSDepTime       ArrTime    CRSArrTime     FlightNum  \
count  1.247486e+06  1.247486e+06  1.247486e+06  1.247486e+06  1.247486e+06   
mean   1.558832e+03  1.487949e+03  1.616749e+03  1.652458e+03  2.276526e+03   
std    4.543300e+02  4.211782e+02  5.839416e+02  4.617372e+02  1.997547e+03   
min    1.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00  1.000000e+00   
25%    1.232000e+03  1.150000e+03  1.326000e+03  1.340000e+03  6.370000e+02   
50%    1.618000e+03  1.529000e+03  1.737000e+03  1.722000e+03  1.589000e+03   
75%    1.924000e+03  1.830000e+03  2.048000e+03  2.022000e+03  3.676000e+03   
max    2.400000e+03  2.359000e+03  2.400000e+03  2.359000e+03  9.741000e+03   

       ...      Distance        TaxiIn       TaxiOut  Cancelled   Diverted  \
count  ...  1.247486e+06  1.247486e+06  1.247486e+06  1247486.0  1247486.0   
mean   ...  7.415867e+02  7.297232e+00  2.066033e+01        0.0        0.0   
std    ...  5.593643e+02  6.033239e+00  1.667983e+01        0.0        0.0   
min    ...  1.100000e+01  0.000000e+00  0.000000e+00        0.0        0.0   
25%    ...  3.340000e+02  4.000000e+00  1.100000e+01        0.0        0.0   
50%    ...  5.950000e+02  6.000000e+00  1.600000e+01        0.0        0.0   
75%    ...  9.720000e+02  8.000000e+00  2.400000e+01        0.0        0.0   
max    ...  4.962000e+03  2.400000e+02  4.220000e+02        0.0        0.0   

       CarrierDelay  WeatherDelay      NASDelay  SecurityDelay  \
count  1.247486e+06  1.247486e+06  1.247486e+06   1.247486e+06   
mean   1.917943e+01  3.703355e+00  1.502162e+01   9.013728e-02   
std    4.354624e+01  2.149153e+01  3.383308e+01   2.022716e+00   
min    0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00   
25%    0.000000e+00  0.000000e+00  0.000000e+00   0.000000e+00   
50%    2.000000e+00  0.000000e+00  2.000000e+00   0.000000e+00   
75%    2.100000e+01  0.000000e+00  1.500000e+01   0.000000e+00   
max    2.436000e+03  1.352000e+03  1.357000e+03   3.920000e+02   

       LateAircraftDelay  
count       1.247486e+06  
mean        2.529649e+01  
std         4.205489e+01  
min         0.000000e+00  
25%         0.000000e+00  
50%         8.000000e+00  
75%         3.300000e+01  
max         1.316000e+03  

[8 rows x 25 columns]

In [5]:
delayedFlights.dtypes

Unnamed: 0             int64
Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
DepTime              float64
CRSDepTime             int64
ArrTime              float64
CRSArrTime             int64
UniqueCarrier         object
FlightNum              int64
TailNum               object
ActualElapsedTime    float64
CRSElapsedTime       float64
AirTime              float64
ArrDelay             float64
DepDelay             float64
Origin                object
Dest                  object
Distance               int64
TaxiIn               float64
TaxiOut              float64
Cancelled              int64
CancellationCode      object
Diverted               int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

In [6]:
#Primer elimino els atributs que no són numèrics, per facilitar l'estudi de les regressions. Si els converteixo en dummies m'apareixen 6000 columnes, pel que no em serà fàcil treure conclusions.

numerics = delayedFlights
numerics.drop(["Unnamed: 0","UniqueCarrier", "TailNum", "Origin", "Dest", "CancellationCode"], axis=1, inplace=True)
print(numerics)

C:\Users\Anna\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


         Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
3        2008      1           3          4   1829.0        1755   1959.0   
5        2008      1           3          4   1937.0        1830   2037.0   
7        2008      1           3          4   1644.0        1510   1845.0   
9        2008      1           3          4   1452.0        1425   1640.0   
11       2008      1           3          4   1323.0        1255   1526.0   
...       ...    ...         ...        ...      ...         ...      ...   
1936751  2008     12          13          6    921.0         830   1112.0   
1936752  2008     12          13          6   1552.0        1520   1735.0   
1936753  2008     12          13          6   1250.0        1220   1617.0   
1936754  2008     12          13          6    657.0         600    904.0   
1936755  2008     12          13          6   1007.0         847   1149.0   

         CRSArrTime  FlightNum  ActualElapsedTime  ...  Distance  TaxiIn  \

CREACIÓ TRAIN TEST

In [7]:
from sklearn.model_selection import train_test_split
numerics = numerics.sample(100000, random_state=0)

In [8]:
# Indico quin vull que sigui el meu target o input o y
y = np.array(numerics["ArrDelay"])
x = np.array(numerics)

#Creo el train test
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)

REGRESSIÓ LINEAL MÚLTIPLE

In [9]:
#Primer faré una regressió lineal múltiple, importo la llibreria 

from sklearn.linear_model import LinearRegression


In [10]:
# Creo el model de regressió
model = LinearRegression(n_jobs=-1).fit(X_train, y_train)

r_sq = model.score(X_test, y_test)
print(f"coefficient of determination: {r_sq}")

print(f"intercept: {model.intercept_}")

print(f"coefficients: {model.coef_}")

coefficient of determination: 1.0
intercept: 8.526512829121202e-14
coefficients: [ 0.00000000e+00  2.25514052e-15  4.52383356e-17  3.14819615e-15
 -8.37004077e-17 -5.11743425e-17  3.12250226e-17  1.33140027e-16
 -9.71445147e-17  1.74418605e-01 -2.32558140e-01  5.81395349e-02
  6.39534884e-01  2.32558140e-01  1.11455983e-16  5.81395349e-02
  5.81395349e-02  0.00000000e+00 -2.77555756e-17  1.27906977e-01
  1.27906977e-01  1.27906977e-01  1.27906977e-01  1.27906977e-01]


In [11]:
prediccioLineal = model.predict(X_test)
print(prediccioLineal)

[122.  39.  27. ...  43.  36.  83.]


In [12]:
# Comparació X-test amb la predicció
pred_lineal = pd.DataFrame({"Actual":y_test, "Predicted":prediccioLineal})
pred_lineal

#No entenc perquè em surt igual

Actual  Predicted
0       122.0      122.0
1        39.0       39.0
2        27.0       27.0
3        42.0       42.0
4        52.0       52.0
...       ...        ...
19995    45.0       45.0
19996    18.0       18.0
19997    43.0       43.0
19998    36.0       36.0
19999    83.0       83.0

[20000 rows x 2 columns]

REGRESSIÓ POLINOMINAL

In [13]:
# Importo les llibreries
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Els outputs x i inputs y seran els mateixos que l'anterior regressió

#Creo la instancia necessària
transformer = PolynomialFeatures(degree=2, include_bias=False)
X = transformer.fit_transform(x)
X.reshape((-1,1))
#Creo el train test de nou amb la X correcte
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)


In [14]:
# Creo el model de regressió i l'aplico
model = LinearRegression(n_jobs=-1).fit(X_train, y_train)

r_sq = model.score(X_test, y_test)
print(f"coefficient of determination: {r_sq}")

print(f"intercept: {model.intercept_}")

print(f"coefficients: {model.coef_}")

coefficient of determination: 1.0
intercept: 9.741540907270974e-12
coefficients: [ 1.22421090e-19  2.03820373e-16  1.42432613e-16  3.27200357e-17
  5.40237614e-17 -1.13739584e-17  2.13875819e-17  3.49705493e-18
 -3.68798145e-18  4.32578851e-08 -5.76771802e-08  1.44192951e-08
  1.58612246e-07  5.76771802e-08  1.63107726e-17  1.44192950e-08
  1.44192950e-08  2.12774676e-18  1.75505227e-18  3.17224491e-08
  3.17224491e-08  3.17224491e-08  3.17224491e-08  3.17224491e-08
 -2.08708918e-18  6.03934822e-18  6.40965713e-18  3.99508384e-18
 -3.09336432e-18  2.34448132e-18  2.38651533e-19 -3.05143619e-19
  6.77626358e-21  8.68618334e-05 -1.15815778e-04  2.89539445e-05
  3.18493389e-04  1.15815778e-04  6.85673171e-19  2.89539445e-05
  2.89539445e-05  3.04931861e-20  0.00000000e+00  6.36986778e-05
  6.36986778e-05  6.36986778e-05  6.36986778e-05  6.36986778e-05
  2.82208518e-17  2.05455733e-17 -1.38575807e-16 -4.37608984e-18
 -2.53881748e-18 -5.65164702e-18 -9.35471790e-19 -8.49904918e-19
 -5.38234

In [15]:
prediccioPolinominal = model.predict(X_test)
print(f"predicted response:\n{prediccioPolinominal}")

predicted response:
[122.  39.  27. ...  43.  36.  83.]


In [16]:
# Comparació X-test amb la predicció
pred_polinominal = pd.DataFrame({"Actual":y_test, "Predicted":prediccioPolinominal})
pred_polinominal

#No entenc perquè em surt igual

Actual  Predicted
0       122.0      122.0
1        39.0       39.0
2        27.0       27.0
3        42.0       42.0
4        52.0       52.0
...       ...        ...
19995    45.0       45.0
19996    18.0       18.0
19997    43.0       43.0
19998    36.0       36.0
19999    83.0       83.0

[20000 rows x 2 columns]

DECISION TREE REGRESSOR

In [17]:
# Importo les llibreries
from sklearn.tree import DecisionTreeRegressor

# Els outputs x i inputs y seran els mateixos que l'anterior regressió

#Creo la instancia necessària
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

In [18]:
prediccioTree = regressor.predict(X_test)
print(f"predicted response:\n{prediccioTree}")

predicted response:
[122.  39.  27. ...  43.  36.  83.]


In [19]:
# Comparació X-test amb la predicció
pred_Tree = pd.DataFrame({"Actual":y_test, "Predicted":prediccioTree})
pred_Tree

#No entenc perquè em surt igual

Actual  Predicted
0       122.0      122.0
1        39.0       39.0
2        27.0       27.0
3        42.0       42.0
4        52.0       52.0
...       ...        ...
19995    45.0       45.0
19996    18.0       18.0
19997    43.0       43.0
19998    36.0       36.0
19999    83.0       83.0

[20000 rows x 2 columns]

### Exercici 2
Compara’ls en base al MSE i al R2 .


In [20]:
import statsmodels.api as sm
from sklearn import metrics

In [21]:
print("REGRESSIÓ LINEAL")
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, prediccioLineal))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, prediccioLineal))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, prediccioLineal)))

REGRESSIÓ LINEAL
Mean Absolute Error: 1.7859509426898511e-13
Mean Squared Error: 4.907812483092654e-26
Root Mean Squared Error: 2.2153583193453502e-13


In [22]:
print("REGRESSIÓ POLINOMINAL")
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, prediccioPolinominal))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, prediccioPolinominal))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, prediccioPolinominal)))

REGRESSIÓ POLINOMINAL
Mean Absolute Error: 3.4243665680833146e-13
Mean Squared Error: 2.746917523940014e-25
Root Mean Squared Error: 5.241104391194678e-13


In [23]:
print("DECISION TREE REGRESSOR")
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, prediccioTree))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, prediccioTree))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, prediccioTree)))

DECISION TREE REGRESSOR
Mean Absolute Error: 0.01635
Mean Squared Error: 0.41935
Root Mean Squared Error: 0.6475723897758459


### Exercici 3
Entrena’ls utilitzant els diferents paràmetres que admeten.

CANVIEM PARÀMETRES DE LA REGRESSIÓ LINEAL

In [24]:
# Creo el model de regressió
model = LinearRegression(fit_intercept = False, normalize=True, n_jobs=-1).fit(X_train, y_train)

r_sq = model.score(X_test, y_test)
print(f"coefficient of determination: {r_sq}")

print(f"intercept: {model.intercept_}")

print(f"coefficients: {model.coef_}")

C:\Users\Anna\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


coefficient of determination: 1.0
intercept: 0.0
coefficients: [-4.84628442e-12 -2.48677398e-08 -2.04300821e-07 -1.19744257e-07
  1.42077538e-07 -1.71605380e-07 -1.85155991e-07  1.47736012e-10
 -2.31554081e-07 -2.14349746e-07  1.49193218e-07 -5.25919096e-08
  2.20749683e-07 -2.74822614e-07  1.17568035e-07 -9.41946106e-09
  4.29526142e-08 -7.08787719e-08 -2.68606276e-09  3.13684329e-08
  1.71670345e-08  2.55645243e-08  3.26464843e-08  3.30702208e-08
  2.41393802e-15  1.23842642e-11  1.01743443e-10  5.96335962e-11
 -7.07557453e-11  8.54608426e-11  9.22091605e-11 -7.35736473e-14
  1.15315777e-10  8.68244811e-05 -1.15745099e-04  2.89206761e-05
  3.18574500e-04  1.15745161e-04 -5.85498175e-11  2.89206546e-05
  2.89206285e-05  4.68126480e-10 -2.19455400e-09  6.36883181e-05
  6.36883252e-05  6.36883210e-05  6.36883175e-05  6.36883173e-05
  7.28355358e-16  4.49678964e-16  6.30406246e-16  1.85881943e-17
  1.79464940e-17  9.05300708e-18  4.14002408e-17  5.92506164e-19
  1.38699192e-10 -5.6900020

In [25]:
prediccioLineal = model.predict(X_test)
print(prediccioLineal)

[122.  39.  27. ...  43.  36.  83.]


In [26]:
# Comparació X-test amb la predicció
pred_lineal = pd.DataFrame({"Actual":y_test, "Predicted":prediccioLineal})
pred_lineal

#No entenc perquè em surt igual

Actual  Predicted
0       122.0      122.0
1        39.0       39.0
2        27.0       27.0
3        42.0       42.0
4        52.0       52.0
...       ...        ...
19995    45.0       45.0
19996    18.0       18.0
19997    43.0       43.0
19998    36.0       36.0
19999    83.0       83.0

[20000 rows x 2 columns]

CANVIEM PARÀMETRES DE LA REGRESSIÓ POLINOMINAL

In [27]:
#Creo la instancia necessària
transformer = PolynomialFeatures(degree=3, include_bias=True, interaction_only=True)
X = transformer.fit_transform(x)
X.reshape((-1,1))
#Creo el train test de nou amb la X correcte
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)


In [28]:
# Creo el model de regressió i l'aplico
model = LinearRegression(n_jobs=-1).fit(X_train, y_train)

r_sq = model.score(X_test, y_test)
print(f"coefficient of determination: {r_sq}")

print(f"intercept: {model.intercept_}")

print(f"coefficients: {model.coef_}")

coefficient of determination: 1.0
intercept: 0.00016865601577364941
coefficients: [-7.17138572e-17 -8.39919234e-08  4.53184445e-08 ... -3.44700174e-16
  0.00000000e+00  3.77823947e-15]


In [29]:
prediccioPolinominal = model.predict(X_test)
print(f"predicted response:\n{prediccioPolinominal}")

predicted response:
[122.  39.  27. ...  43.  36.  83.]


In [30]:
# Comparació X-test amb la predicció
pred_polinominal = pd.DataFrame({"Actual":y_test, "Predicted":prediccioPolinominal})
pred_polinominal

#No entenc perquè em surt igual

Actual  Predicted
0       122.0      122.0
1        39.0       39.0
2        27.0       27.0
3        42.0       42.0
4        52.0       52.0
...       ...        ...
19995    45.0       45.0
19996    18.0       18.0
19997    43.0       43.0
19998    36.0       36.0
19999    83.0       83.0

[20000 rows x 2 columns]

CANVIEM PARÀMETRES DE LA REGRESSIÓ D'ARBRE (DECISION TREE REGRESSION)




### Exercici 4
Compara el seu rendiment utilitzant l’aproximació traint/test o utilitzant totes les dades (validació interna)




REGRESSIÓ LINEAL MÚLTIPLE

In [31]:
# Creo el model de regressió
model = LinearRegression(n_jobs=-1).fit(x, y)

r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

print(f"intercept: {model.intercept_}")

print(f"coefficients: {model.coef_}")

coefficient of determination: 1.0
intercept: 5.826450433232822e-13
coefficients: [ 0.00000000e+00  1.27051147e-14  1.39862080e-15 -3.82415318e-14
 -3.03576608e-16  1.01915004e-16 -1.90819582e-16  1.26634814e-16
  0.00000000e+00  1.74418605e-01 -2.32558140e-01  5.81395349e-02
  6.39534884e-01  2.32558140e-01  2.79290480e-16  5.81395349e-02
  5.81395349e-02 -1.21430643e-17  2.77555756e-17  1.27906977e-01
  1.27906977e-01  1.27906977e-01  1.27906977e-01  1.27906977e-01]


In [32]:
prediccioLineal = model.predict(x)
print(prediccioLineal)

[ 16.  99.  29. ... 110.  54.  18.]


In [33]:
# Comparació X-test amb la predicció
pred_lineal = pd.DataFrame({"Actual":y, "Predicted":prediccioLineal})
pred_lineal

#No entenc perquè em surt igual

Actual  Predicted
0        16.0       16.0
1        99.0       99.0
2        29.0       29.0
3        32.0       32.0
4        23.0       23.0
...       ...        ...
99995    23.0       23.0
99996    26.0       26.0
99997   110.0      110.0
99998    54.0       54.0
99999    18.0       18.0

[100000 rows x 2 columns]

In [34]:
print("REGRESSIÓ LINEAL")
print('Mean Absolute Error:', metrics.mean_absolute_error(y, prediccioLineal))
print('Mean Squared Error:', metrics.mean_squared_error(y, prediccioLineal))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y, prediccioLineal)))

REGRESSIÓ LINEAL
Mean Absolute Error: 1.5488041071876069e-13
Mean Squared Error: 4.109286176381836e-26
Root Mean Squared Error: 2.0271374340142397e-13


REGRESSIÓ POLINOMINAL

In [35]:
#Creo la instancia necessària
transformer = PolynomialFeatures(degree=2, include_bias=False)
X = transformer.fit_transform(x)
X.reshape((-1,1))


array([[2.008e+03],
       [2.000e+00],
       [2.600e+01],
       ...,
       [0.000e+00],
       [0.000e+00],
       [1.690e+02]])

In [36]:
# Creo el model de regressió i l'aplico
model = LinearRegression(n_jobs=-1).fit(X, y)

r_sq = model.score(X, y)
print(f"coefficient of determination: {r_sq}")

print(f"intercept: {model.intercept_}")

print(f"coefficients: {model.coef_}")

coefficient of determination: 1.0
intercept: 6.181721801112872e-13
coefficients: [-6.93341280e-20 -4.04747918e-16  1.34813764e-17  3.03989960e-16
 -5.40949121e-17 -1.23267011e-16  1.11930322e-16  5.73644593e-17
 -3.87305815e-17  4.32578851e-08 -5.76771802e-08  1.44192951e-08
  1.58612246e-07  5.76771802e-08  2.92375259e-17  1.44192951e-08
  1.44192951e-08  2.76471554e-18 -7.18283939e-18  3.17224491e-08
  3.17224491e-08  3.17224491e-08  3.17224491e-08  3.17224491e-08
 -3.59141970e-19  1.69347297e-17 -6.29091370e-18 -3.07197674e-18
  1.45350854e-18 -1.18923426e-18  7.42000862e-19 -5.09913834e-19
  6.09863722e-20  8.68618334e-05 -1.15815778e-04  2.89539445e-05
  3.18493389e-04  1.15815778e-04 -3.37119113e-19  2.89539445e-05
  2.89539445e-05  1.86347248e-19 -1.67712524e-19  6.36986778e-05
  6.36986778e-05  6.36986778e-05  6.36986778e-05  6.36986778e-05
  8.81399787e-17  2.96756868e-17 -5.67131835e-16  4.24448210e-18
  3.23905399e-18  6.48191963e-19  1.60131579e-18 -5.78099987e-19
  5.08510

In [37]:
prediccioPolinominal = model.predict(X)
print(f"predicted response:\n{prediccioPolinominal}")

predicted response:
[ 16.  99.  29. ... 110.  54.  18.]


In [38]:
# Comparació X-test amb la predicció
pred_polinominal = pd.DataFrame({"Actual":y, "Predicted":prediccioPolinominal})
pred_polinominal

#No entenc perquè em surt igual

Actual  Predicted
0        16.0       16.0
1        99.0       99.0
2        29.0       29.0
3        32.0       32.0
4        23.0       23.0
...       ...        ...
99995    23.0       23.0
99996    26.0       26.0
99997   110.0      110.0
99998    54.0       54.0
99999    18.0       18.0

[100000 rows x 2 columns]

In [39]:
print("REGRESSIÓ POLINOMINAL")
print('Mean Absolute Error:', metrics.mean_absolute_error(y, prediccioPolinominal))
print('Mean Squared Error:', metrics.mean_squared_error(y, prediccioPolinominal))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y, prediccioPolinominal)))


REGRESSIÓ POLINOMINAL
Mean Absolute Error: 2.3955818662102503e-13
Mean Squared Error: 1.0287020560438499e-25
Root Mean Squared Error: 3.207338547836586e-13


DECISION TREE REGRESSOR

In [40]:
#Creo la instancia necessària
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(x,y)

DecisionTreeRegressor(random_state=0)

In [41]:
prediccioTree = regressor.predict(x)
print(f"predicted response:\n{prediccioTree}")

predicted response:
[ 16.  99.  29. ... 110.  54.  18.]


In [42]:
# Comparació X-test amb la predicció
pred_Tree = pd.DataFrame({"Actual":y, "Predicted":prediccioTree})
pred_Tree

#No entenc perquè em surt igual

Actual  Predicted
0        16.0       16.0
1        99.0       99.0
2        29.0       29.0
3        32.0       32.0
4        23.0       23.0
...       ...        ...
99995    23.0       23.0
99996    26.0       26.0
99997   110.0      110.0
99998    54.0       54.0
99999    18.0       18.0

[100000 rows x 2 columns]

In [43]:
print("DECISION TREE REGRESSOR")
print('Mean Absolute Error:', metrics.mean_absolute_error(y, prediccioTree))
print('Mean Squared Error:', metrics.mean_squared_error(y, prediccioTree))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y, prediccioTree)))

DECISION TREE REGRESSOR
Mean Absolute Error: 0.0
Mean Squared Error: 0.0
Root Mean Squared Error: 0.0


## NIVELL 2




### Exercici 5
Realitza algun procés d’enginyeria de variables per millorar-ne la predicció





## NIVELL 3


### Exercici 6
No utilitzis la variable DepDelay a l’hora de fer prediccions